web_dict = { 
  "extras_price": "$0.00", 
  "revenue": "$124.00", 
  "payment_method": "stripe", 
  "rating_comment_presence": "", 
  "address": "1/121 Stock Rd, Unit", 
  "custom_data": "Please select an option below                                                     : Google", 
  "updated_at": "2018-10-25T11:06:33+10:00", 
  "giftcard_amount": "$0.00", 
  "assigned_teams": "Assigned team(s): Team Euclid", 
  "last_name": "Nall", 
  "assigned_teams_team": "s", 
  "price_adjustment": "$0.00", 
  "duration": "0 hrs 0 mins", 
  "time_estimate": "0 hours 0 minutes", 
  "team_share_amount": "Team Euclid - $67.64", 
  "team_details": "[{u'phone': u'+6 (142) 695-8397', u'first_name': u'Irene & Yong', u'last_name': u'', u'image_url': u'', u'name': u'Irene & Yong', u'title': u'Team Euclid', u'id': u'8447'}]", 
  "id": "14450", 
  "custom_fields": { 
    "drop_down:65c938ba-a125-48ba-a21f-9fb34350ab24": "Google" 
  }, 
  "city": "Attadale", 
  "first_name": "Zoe", 
  "pricing_parameters_price": "$20.00", 
  "service": "2 Bedroom", 
  "is_new_customer": "True", 
  "subtotal": "$124.00", 
  "service_time": "12:00 - 12:30", 
  "tip": "$0.00", 
  "rating_comment": "", 
  "source": "client-site", 
  "state": "WA", 
  "extras": "", 
  "is_first_recurring": "False", 
  "company_name": "", 
  "service_date_timestamp": "2018-10-26T12:00:00+10:00", 
  "service_category": "House Clean", 
  "email": "karenann1@hotmail.com", 
  "final_price": "$124.00", 
  "pricing_parameters": "1 x Bathroom", 
  "tip_amount": "$0.00", 
  "sms_notifications_enabled": "NO", 
  "name": "Zoe Nall", 
  "cancellation_type": "", 
  "service_name_for_invoice": "2 Bedroom", 
  "rating_color": "", 
  "customer_notes": "Home", 
  "phone": "0412328484", 
  "team_share_percent": "Team Euclid - 54.55%", 
  "price_adjustment_comment": "", 
  "teams_share": { 
    "8447": "Pay: $67.64<br/>Tip: $0.00<br/>Total Earned: $67.64" 
  },
  "charge_amount": "$124.00", 
  "rating_text": "", 
  "discount_amount": "$0.00", 
  "customer": { 
    "last_name": "Nall", 
    "updated_at": "2018-10-24T13:10:19+10:00", 
    "referral_balance_redeemed": "0.0", 
    "referral_code": "464abcbc1c2cdcf8", 
    "id": "8674", 
    "city": "Attadale", 
    "first_name": "Zoe", 
    "referral_balance_pending": "0.0", 
    "title": "", 
    "state": "WA", 
    "referral_balance_earned": "0.0", 
    "company_name": "", 
    "email": "karenann1@hotmail.com", 
    "profile_url": "https://maid2match.launch27.com/admin/customers/8674/edit", 
    "zip": "6157", 
    "tags": "", 
    "phone": "0412328484", 
    "address": "1/121 Stock Rd, Unit", 
    "name": "Zoe Nall", 
    "notes": "", 
    "pending_email": "", 
    "image_url": "", 
    "created_at": "2018-10-24T13:10:19+10:00" 
  }, 
  "staff_notes": "", 
  "team_share_total": "Team Euclid - $67.64", 
  "zip": "6157", 
  "discount": "", 
  "service_date_for_invoice": "October 26, 2018", 
  "revenue_with_tax": "$124.00", 
  "created_at": "2018-10-24T13:10:19+10:00", 
  "cancelled_by": "", 
  "team_share_tip": "Team Euclid - $0.00", 
  "cancellation_date": "", 
  "frequency": "1 Time Service", 
  "revenue_with_tax_and_tip": "$124.00", 
  "sales_tax": "$0.00", 
  "cancellation_type_text": "", 
  "cancellation_reason": "", 
  "service_date": "2018-10-26" 
} 